#!/usr/bin/env bash
# afergon-ai/scripts/init-project.sh
#
# Run from the root of any project to opt-in to afergon-ai as the active orchestrator.
# Creates .pi/APPEND_SYSTEM.md and openspec/config.yaml.
#
# Usage:
#   bash /path/to/afergon-ai/scripts/init-project.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_ROOT="$(dirname "$SCRIPT_DIR")"
TARGET_DIR="$(pwd)"
PI_DIR="$TARGET_DIR/.pi"
APPEND_SYSTEM="$PI_DIR/APPEND_SYSTEM.md"
OPENSPEC_DIR="$TARGET_DIR/openspec"
CONFIG_FILE="$OPENSPEC_DIR/config.yaml"

# Infer project name from directory
PROJECT_NAME="$(basename "$TARGET_DIR")"

echo ""
echo "afergon-ai — project initialization"
echo "====================================="
echo "Project: $PROJECT_NAME"
echo "Directory: $TARGET_DIR"
echo ""

# ── Orchestrator ──────────────────────────────────────────────────────────────

mkdir -p "$PI_DIR"

if [ -f "$APPEND_SYSTEM" ]; then
  echo "Warning: $APPEND_SYSTEM already exists."
  read -r -p "Overwrite? [y/N] " confirm
  if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Skipping orchestrator setup."
  else
    awk '/^---/{found++; next} found==2{print}' "$PACKAGE_ROOT/prompts/afergon-ai.md" > "$APPEND_SYSTEM"
    echo "✔ Created $APPEND_SYSTEM"
  fi
else
  awk '/^---/{found++; next} found==2{print}' "$PACKAGE_ROOT/prompts/afergon-ai.md" > "$APPEND_SYSTEM"
  echo "✔ Created $APPEND_SYSTEM"
fi

# ── Memory system ─────────────────────────────────────────────────────────────

echo ""
echo "Memory system"
echo "-------------"
echo "Select the memory system this project will use:"
echo ""
echo "  1) Engram       — Pi-native persistent memory (recommended if installed)"
echo "  2) Obsidian     — Markdown vault (requires vault path)"
echo "  3) memory.md    — Simple append-only file at openspec/MEMORY.md"
echo "  4) None         — No memory"
echo ""
read -r -p "Select [1-4, default 4]: " mem_choice

MEMORY_SYSTEM="none"
OBSIDIAN_VAULT=""
OBSIDIAN_FOLDER=""

case "${mem_choice:-4}" in
  1)
    MEMORY_SYSTEM="engram"
    echo "✔ Memory: Engram"
    ;;
  2)
    MEMORY_SYSTEM="obsidian"
    read -r -p "Vault path (e.g. ~/Documents/Obsidian/MyVault): " OBSIDIAN_VAULT
    OBSIDIAN_VAULT="${OBSIDIAN_VAULT/#\~/$HOME}"
    read -r -p "Folder inside vault [default: Projects/$PROJECT_NAME]: " OBSIDIAN_FOLDER
    OBSIDIAN_FOLDER="${OBSIDIAN_FOLDER:-Projects/$PROJECT_NAME}"
    echo "✔ Memory: Obsidian ($OBSIDIAN_VAULT/$OBSIDIAN_FOLDER)"
    ;;
  3)
    MEMORY_SYSTEM="memory-md"
    echo "✔ Memory: memory.md (openspec/MEMORY.md)"
    ;;
  *)
    MEMORY_SYSTEM="none"
    echo "✔ Memory: none"
    ;;
esac

# ── Write openspec/config.yaml ────────────────────────────────────────────────

mkdir -p "$OPENSPEC_DIR"

if [ -f "$CONFIG_FILE" ]; then
  echo ""
  echo "Warning: $CONFIG_FILE already exists."
  read -r -p "Overwrite? [y/N] " confirm
  if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Skipping config.yaml update."
    CONFIG_FILE=""
  fi
fi

if [ -n "$CONFIG_FILE" ]; then
  cat > "$CONFIG_FILE" << EOF
# afergon-ai project configuration
# Generated by init-project.sh — edit manually if needed.

project:
  name: $PROJECT_NAME

memory:
  system: $MEMORY_SYSTEM
EOF

  if [ "$MEMORY_SYSTEM" = "obsidian" ]; then
    cat >> "$CONFIG_FILE" << EOF
  vault: $OBSIDIAN_VAULT
  folder: $OBSIDIAN_FOLDER
EOF
  fi

  if [ "$MEMORY_SYSTEM" = "memory-md" ]; then
    cat >> "$CONFIG_FILE" << EOF
  path: openspec/MEMORY.md
EOF
  fi

  echo "✔ Created $CONFIG_FILE"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "afergon-ai is ready."
echo ""
echo "Available skills (global):"
echo "  /skill:debate        /skill:breakdown    /skill:specify"
echo "  /skill:plannify      /skill:implement    /skill:design"
echo "  /skill:afergon-review                    /skill:detect-skills"
echo ""
echo "Open Pi from this directory to start."
